### PR TITLE
looks like we need not call topic_destroy

### PR DESCRIPTION
**Pull request by ibawt**
well that was annoying to make a PR, this is why I told you to not fork it...

I think we'll have to transfer ownership.

Anyhoo:
## wat
1. Fix logic error in init
2. do not call destroy
## why
- when I call topic_destory the kafka instance seems to never exit.  When I left it out, everything goes through super easy.  I have a feeling there was a slight change in the ordering of the delivery.
## however
- this screams like a memory leak though.  I'd prefer to not keep a list of previously used topics...
## Other things
- why isn't CI working for this branch?
- why didn't our CI catch this 

cc @DerekStride

### CODE REVIEW

**Comment by ibawt** [comment]
@DerekStride you'll have to carry the ball on this.  

Can you:
1. see why CI isn't working for branches
2. make sure that CI is using the same version of librdkafka ( please lock the version down )
3. see if this works for you?

**Comment by ibawt** [comment]
looks like CI is working now, idk :(

**Comment by DerekStride** [comment]
> why didn't our CI catch this

I had locked the version of librdkafka to the same one as homebrew before they updated it. We should probably change it to reference the newest release.

**Comment by DerekStride** [comment]
We'll probably want to change this https://github.com/Shopify/ckafka/blob/master/circle.yml#L11 to:

``` yaml
- >
  add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu trusty main universe";
  apt-get update;
  apt-get install librdkafka-dev;
```

**Comment by ibawt** [comment]
you can lock the version with apt-get install ibrdkafka-dev=version_number

**Comment by DerekStride** [comment]
Actually the apt package is only current up until 0.8.x so I still need to use git to build the correct version.

**Comment by DerekStride** [comment]
I verified that the tests would fail on CI in [Build #13](https://circleci.com/gh/Shopify/ckafka/13). LGTM 👍

**Pull request merged**
